const ENVIRONMENTS = [
    "REPOSITORY_COMPONENTS_FOLDER",
]

const OPTIONAL_ENVIRONMENTS = [
    "REPOSITORY_COMPONENTS_FILE",
    "HEADLESS",
]

const OPTIONAL_ENVIRONMENTS_DEFAULTS = {
    HEADLESS: "false",
}

const OPTIONAL_ENVIRONMENTS_ALLOWED_VALUES = {
    HEADLESS: ["true", "false", "1", "0"],
}

const EXTENSION_JS_FILES = [".js", ".jsx", ".ts", ".tsx"];
const EXTENSION_CSS_FILES = [".css"];

module.exports = { ENVIRONMENTS, OPTIONAL_ENVIRONMENTS, OPTIONAL_ENVIRONMENTS_DEFAULTS, OPTIONAL_ENVIRONMENTS_ALLOWED_VALUES, EXTENSION_JS_FILES, EXTENSION_CSS_FILES };