const ENVIRONMENTS = [
    "REPOSITORY_COMPONENTS_FOLDER",
]

const OPTIONAL_ENVIRONMENTS = [
    "REPOSITORY_COMPONENTS_FILE"
]

const EXTENSION_JS_FILES = [".js", ".jsx", ".ts", ".tsx"];
const EXTENSION_CSS_FILES = [".css"];

module.exports = { ENVIRONMENTS,OPTIONAL_ENVIRONMENTS, EXTENSION_JS_FILES, EXTENSION_CSS_FILES };